const products = [
    {
        "productName": "Kachi Ghani Mustard Oil",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/276756_7-fortune-kachi-ghani-mustard-oil.jpg",
        "brandName": "Fortune",
        "ratings": 4.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Edible Oil",
        "category": "Foodgrains, Oils and Masala",
        "size": ["500 ml", "1 L"],
        "mrp": ["96", "186"],
        "offer": 19,
        "description": "Fortune Kachi Ghani is a premium mustard oil that enhances the taste of your food. We use a traditional process to extract pure mustard oil, so that the natural properties, antioxidants and essential oils are retained. The strong aroma and taste of mustard oil adds a spicy flavor to your cooking."
    },
    {
        "productName": "Onion",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000148_28-fresho-onion.jpg",
        "brandName": "Fresho",
        "ratings": 3.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["1 kg", "2 kg"],
        "mrp": ["92.50", "185"],
        "offer": 28,
        "description": "Onion is a vegetable which is almost like a staple in Indian food. This is also known to be one of the essential ingredients of raw salads. They come in different colours like white, red or yellow and are quite in demand in cold salads and hot soups. You can dice, slice or cut it in rings and put it in burgers and sandwiches. Onions emit a sharp flavour and fragrance once they are fried; it is due to the sulphur compound in the vegetable"
    },
    {
        "productName": "Potato",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000159_25-fresho-potato.jpg",
        "brandName": "Fresho",
        "ratings": 3.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["1 kg", "2 kg"],
        "mrp": ["56.25", "112.50"],
        "offer": 25,
        "description": "Fresho Potatoes are nutrient-dense, non-fattening and have reasonable amount of calories. Include them in your regular meals so that the body receives a good supply of carbohydrates, dietary fibers and essential minerals such as copper, magnesium, and iron. In India, potatoes are probably the second-most consumed vegetables after onions."
    },
    {
        "productName": "Lemon",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000127_17-fresho-lemon.jpg",
        "brandName": "Fresho",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Herbs and seasonings",
        "category": "Fruits and vegetables",
        "size": ["250 g", "500 g"],
        "mrp": ["36.25", "71.25"],
        "offer": 20,
        "description": "With a segmented flesh that has a unique pleasant aroma and a strong sour taste, lemons are round/oval and have a yellow, texturized external peel."
    },
    {
        "productName": "Chilli - Picador",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/30001773_3-fresho-chilli-picador.jpg",
        "brandName": "Fresho",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Herbs and seasonings",
        "category": "Fruits and vegetables",
        "size": ["1 kg"],
        "mrp": ["245"],
        "offer": 20,
        "description": "Picdor Chilli have thick sharp and spicy taste, however the roughness can differ depending on the range of chilly. Some are very sharp, while some have less of flavor in them. It is high in Vitamin A & C. Product image shown is for representation purpose only, the actually product may vary based on season, produce & availability."
    },
    {
        "productName": "India Gate Basmati Rice",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/283426_2-india-gate-basmati-rice-feast-rozzana.jpg",
        "brandName": "India Gate",
        "ratings": 4.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Rice & Rice Products",
        "category": "Foodgrains, oils & Masala",
        "size": ["1 kg", "5 kg"],
        "mrp": ["89", "440"],
        "offer": 15,
        "description": "India Gate Basmati Rice Feast Rozzana is defined by its long grains and amazing aromatic flavour. Having this rice is truly having a feast rozzana (a daily feast); combine it with your veggies and serve a nice pulao. Without this Basmati Rice, your biryanis will seem dull and tasteless. This is the perfect ingredient for different rice recipes. "
    },
    {
        "productName": "Almond/Badam",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40021405_9-bb-popular-almondbadam-californian-giri.jpg",
        "brandName": "BB Popular",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dry fruits",
        "category": "Foodgrains, oils & Masala",
        "size": ["100 gm", "200 gm", "500 gm", "1 kg"],
        "mrp": ["120", "240", "600", "1200"],
        "offer": 10,
        "description": "Almonds come in many varieties and the BB Royal California badam or almonds are premiere choice of many customers at bigbasket. The sweet and nutty taste of the almonds is combined here with hygienically packing to ensure freshness of these Californian Almonds. "
    },
    {
        "productName": "Sugar",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40019396_8-bb-popular-sugar.jpg",
        "brandName": "BB Popular",
        "ratings": 4.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Salt, sugar & Jaggery",
        "category": "Foodgrains, oils & Masala",
        "size": ["1 kg", "2 kg", "5 kg"],
        "mrp": ["55", "110", "275"],
        "offer": 20,
        "description": "Almonds come in many varieties and the BB Royal California badam or almonds are premiere choice of many customers at bigbasket. The sweet and nutty taste of the almonds is combined here with hygienically packing to ensure freshness of these Californian Almonds. "
    },
    {
        "productName": "Fresh Paneer",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40096747_5-amul-fresh-paneer.jpg",
        "brandName": "Amul",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "dairy",
        "category": "Bakery , cakes & Dairy",
        "size": ["200 gm", "500 gm", "1 kg"],
        "mrp": ["75", "190", "300"],
        "offer": 20,
        "description": "Paneer is also called cottage cheese. Amul Fresh Paneer is made from pure milk, hygenically packed untouched by hand. It adheres to FASSAI norms. Amul fresh paneer is a rich source of Protein."
    },
    {
        "productName": "Tomato - Hybrid",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000201_15-fresho-tomato-hybrid.jpg",
        "brandName": "Fresho",
        "ratings": 3.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 gm", "1 kg", "2 kg"],
        "mrp": ["35", "70", "130"],
        "offer": 31,
        "description": "Tomato Hybrids are high-quality fruits compared to desi, local tomatoes. They contain numerous edible seeds and are red in colour due to lycopene, an anti-oxidant. "
    },
    {
        "productName": "Carrot",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000271_13-fresho-carrot-ooty.jpg",
        "brandName": "Fresho",
        "ratings": 3.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 gm", "1 kg"],
        "mrp": ["81.25", "160"],
        "offer": 20,
        "description": "A popular sweet-tasting root vegetable, Carrots are narrow and cone shaped. They have thick, fleshy, deeply colored root, which grows underground, and feathery green leaves that emerge above the ground. While these greens are fresh tasting and slightly bitter, the carrot roots are crunchy textured with a sweet and minty aromatic taste. Fresho brings you the flavour and richness of the finest bright orange, crispy and juicy carrots. "
    },
    {
        "productName": "Palak",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000188_11-fresho-palak.jpg",
        "brandName": "Fresho",
        "ratings": 4.1,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 gm", "1 kg"],
        "mrp": ["13.75", "26.25"],
        "offer": 20,
        "description": "With a sweet, nutty and tangent flavour, Palaks are green leafy vegetables that are succulent and spoon shaped. "
    },
    {
        "productName": "Mint Leaves",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000138_17-fresho-mint-leaves.jpg",
        "brandName": "Fresho",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["100 g", "250 g"],
        "mrp": ["16.25", "36.25"],
        "offer": 20,
        "description": "Mint leaves are tender herbs with gentle stems and have a distinct pleasant aroma, pleasing taste, cool after-sensation and medicinal qualities. They are best used raw or added at the end of cooking in order to maintain their delicate flavour and texture. "
    },
    {
        "productName": "Broccoli",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000063_20-fresho-broccoli.jpg",
        "brandName": "Fresho",
        "ratings": 3.8,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 g", "250 g", "1 Kg"],
        "mrp": ["211.25", "107.50", "421.25"],
        "offer": 20,
        "description": "With a shape resembling that of a cauliflower, Brocollis have clusters of small, tight flower heads. These heads turn bright green on cooking and tastes slightly bitter. "
    },
    {
        "productName": "Capsicum - Yellow",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000323_14-fresho-capsicum-yellow.jpg",
        "brandName": "Fresho",
        "ratings": 3.9,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 g", "1 Kg"],
        "mrp": ["267.50", "533.75"],
        "offer": 20,
        "description": "Leaving a mild fruity flavour on the tastebuds, Yellow capsicums, also known as Yellow bell peppers are bell shaped, medium-sized fruit pods. They have thick and shiny skin with a fleshy texture on the inside."
    },
    {
        "productName": "Cabbage - Red",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000171_14-fresho-cabbage-red.jpg",
        "brandName": "Fresho",
        "ratings": 3.6,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["500 g", "1 Kg"],
        "mrp": ["196.25", "391.25"],
        "offer": 20,
        "description": "It is round, wrapped in purplish red leaf layers. The flavour is more peppery and bold compared to green ones. Its leaves are coarser as they have less water content."
    },
    {
        "productName": "Tinda",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000665_10-fresho-tinda.jpg",
        "brandName": "Fresho",
        "ratings": 3.5,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Fresh Vegetables",
        "category": "Fruits and vegetables",
        "size": ["250 g", "500 g", "1 Kg"],
        "mrp": ["42.50", "85", "170"],
        "offer": 66,
        "description": "Tinda is a small vegetable that looks bigger than a green apple but smaller than a pumpkin. Short and squat like a pumpkin, tindas have a dark green stem and white flesh that is tender and tastes like a cucumber. The seeds within are edible"
    },
    {
        "productName": "Moong Dal",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000434_13-bb-royal-moong-dal.jpg",
        "brandName": "bb Royal",
        "ratings": 4.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 kg"],
        "mrp": ["100", "200"],
        "offer": 30,
        "description": "Moong dal is one of the most popular lentils eaten across India. Packed with protein, BB Royal moong dal packs deliver the finest selection of lentils which is evident from the shine on the lentils. The dal, sourced directly from farmers, is packed in a way that it retains the maximum nutrient value. "
    },
    {
        "productName": "Rajma",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/70001289_7-bb-royal-rajma-whitechitra.jpg",
        "brandName": "bb Royal",
        "ratings": 4.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 kg"],
        "mrp": ["100", "200"],
        "offer": 30,
        "description": "Rajma White is superior to the regular rajma and very soft feel and more delicate flavor. These are white in color. Pulses are low in fat & cholesterol, high in dietary fiber and rich in protein. The normal antioxidants in the beans offer numerous health benefits. These are of finest quality and free from injurious chemicals and powders. "
    },
    {
        "productName": "Toor/Arhar Dal",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000412_15-bb-popular-toorarhar-dal.jpg",
        "brandName": "bb Royal",
        "ratings": 4.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 Kg", "2 Kg", "5 Kg"],
        "mrp": ["80", "160", "320", "800"],
        "offer": 24,
        "description": "Toor Dal is processed with the most superior technology so that the original protein value is kept at its best; each grain of toor dal is the treasure of flavor of finest quality. It allows you with the dual richness of nutrition and appetizing taste for your family. It is fat free and nature contains designed it to absorb various mixtures of seasonings and spices. "
    },
    {
        "productName": "Toor/Arhar Dal",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000428_15-bb-popular-toorarhar-dal.jpg",
        "brandName": "bb Popular",
        "ratings": 3.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 kg", "2 Kg", "5 kg"],
        "mrp": [70, 160, 320, 800],
        "offer": 13,
        "description": "Toor Dal is the most widely-used form of the lentil. It is used in popular recipes. It tastes delicious when cooked and can be digested easily. It also has a long shelf life."
    },
    {
        "productName": "Moong Dal",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/30005420_9-bb-popular-moong-dal.jpg",
        "brandName": "bb Popular",
        "ratings": 2.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 kg"],
        "mrp": [95, 190],
        "offer": 34,
        "description": "Moong beans is a popular food among vegetarians since it contains a lot of proteins and fiber. It is one of the easiest dals to digest and for this reason it is often given to people recovering from an illness, specially a stomach upset. It has antioxidants which is very healthy for the good functioning of the human body. It is a good balanced diet and could be included in our daily."
    },
    {
        "productName": "Soya - Chunks",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40003518_2-nutrela-soya-chunks.jpg",
        "brandName": "Nutrela",
        "ratings": 4.5,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Dals & Pulses",
        "category": "Foodgrains, oils & Masala",
        "size": ["200 g"],
        "mrp": [45],
        "offer": 9,
        "description": "Ruchi Nutrela - soy chunks are an ideal family food-rich in proteins, versatile, and easy to prepare. It is prepared from fully cooked soya bean. They contain over 50% high excellence proteins. After absorbing water, they turn supple and increase to thrice the size. "
    },
    {
        "productName": "Besan Flour/Besan Pith",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/30000155_6-bb-royal-besan-flour.jpg",
        "brandName": "bb Royal",
        "ratings": 4.1,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Atta, Flours & Sooji",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g", "1 Kg"],
        "mrp": [75, 150],
        "offer": 27,
        "description": "Gram flour or besan, is a light yellow color pulses flour made by grinding chickpea (Bengal gram). It is rich in fiber and nutrients, that can improve heart health, stabilize blood sugar and prevent diabetes. Besan is used to make batter for fries like bhajjis, pakodas and vadas. It is also used to make desserts and various kinds of sweet dishes. It can be used as a natural scrub for the skin and is believed to enhance complexion. "
    },
    {
        "productName": "Atta - Whole Wheat",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/126906_7-aashirvaad-atta-whole-wheat.jpg",
        "brandName": "Aashirvaad",
        "ratings": 4.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Atta, Flours & Sooji",
        "category": "Foodgrains, oils & Masala",
        "size": ["1 Kg", "5 Kg", "10 Kg"],
        "mrp": [52, 245, 450],
        "offer": 17,
        "description": "Aashirvaad whole wheat atta is made of zero per cent maida and 100% atta, which makes it extremely nutritious since its packed with health benefits. This also means more fluffy and soft rotis at home. Aashirvaad Atta is also made from the best grains - heavy on the palm, golden amber in colour and hard in bite. It is grounded using the chakki - grinding process for the perfect balance of colour, taste and nutrition. "
    },
    {
        "productName": "Jowar Flour",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40019638_3-organic-tattva-jowar-flour.jpg",
        "brandName": "Organic Tattva",
        "ratings": 3.2,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Atta, Flours & Sooji",
        "category": "Foodgrains, oils & Masala",
        "size": ["500 g"],
        "mrp": [60],
        "offer": 10,
        "description": "Jowar is a millet well known for its health benefits. Organic Tattva's Jowar flour has high contents of calcium, iron, protein and fibre.  "
    },
    {
        "productName": "Maida",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000416_9-bb-royal-maida.jpg",
        "brandName": "bb Royal",
        "ratings": 3.3,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Atta, Flours & Sooji",
        "category": "Foodgrains, oils & Masala",
        "size": ["1 Kg"],
        "mrp": [60],
        "offer": 35,
        "description": "The BB Royal Maida or white flour is an ideal part of any cuisine, including Indian, Chinese and Italian. The maida is sourced from the best of wheat grains, trying to retain optimal fibre value so that you are able to get quality flour, especially with self-rising benefits. "
    },
    {
        "productName": "Cow Ghee",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40126128_2-parsi-dairy-farm-cow-ghee.jpg",
        "brandName": "Parsi Dairy Farm",
        "ratings": 3.4,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Edible Oils & Gees",
        "category": "Foodgrains, oils & Masala",
        "size": ["1 Kg"],
        "mrp": [990],
        "offer": 0,
        "description": "Parsi Cow Ghee is made from the purest and richest of creams using a manual technique that helps obtain maximum flavour and a grainy textured traditional ghee. It is packed in hygienic conditions to keep intact the freshness of pure, authentic ghee. Use it to cook your daily meals and experience the enhanced flavours this ghee brings to your dishes."
    },
    {
        "productName": "Olive Oil - Extra Light",
        "imageUrl": "https://www.bigbasket.com/media/uploads/p/l/40018242_4-borges-olive-oil-extra-light.jpg",
        "brandName": "BORGES",
        "ratings": 3.0,
        "reviews": 0,
        "reviewList": [],
        "subCategory": "Edible Oils & Gees",
        "category": "Foodgrains, oils & Masala",
        "size": ["250 ml", "500 ml", "5 l"],
        "mrp": [375, 700, 5500],
        "offer": 0,
        "description": " "
    },


]

module.exports = products